jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Build with Gradle
      uses: hankolsen/xvfb-action@master
      with:
        run: ./gradlew build jacocoTestReport -xsign -xpublish --warning-mode all
        working-directory: ./
    - continue-on-error: true
      if: matrix.java == '8'
      name: Submit coverage data to codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./RSyntaxTextArea/build/reports/jacoco/test/jacocoTestReport.xml
        name: codecov
    strategy:
      matrix:
        java:
        - '8'
        - '11'
        - '17'
name: Gradle Build
on:
  repository_dispatch:
    types: trigger-ga___gradle.yml
